version: '3'

networks:
  nginx-php-mysql-mongodb-node:

services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
      - mysql-service
      - mongodb-service
    networks:
      - nginx-php-mysql-mongodb-node

  # php
  php-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
      - ./build.sh:/build.sh
    networks:
      - nginx-php-mysql-mongodb-node

  # mysql
  mysql-service:
    image: mysql:8
    container_name: mysql8-container
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    networks:
      - nginx-php-mysql-mongodb-node

  #mongodb
  mongodb-service:
    image: mongo
    container_name: mongo-container
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongodb:/var/lib/mongodb
    ports:
      - "27017:27017"
    networks:
      - nginx-php-mysql-mongodb-node

  # node
  node-service:
    image: node:latest
    container_name: node-container
    working_dir: /var/www/project
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php-mysql-mongodb-node
